/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface PersistentComment {
  'id' : string,
  'content' : string,
  'author' : Principal,
  'timestamp' : Time,
  'videoId' : string,
}
export interface PersistentUserProfile {
  'bio' : string,
  'displayName' : string,
  'followerCount' : bigint,
  'followingCount' : bigint,
}
export interface PersistentVideoPost {
  'id' : string,
  'title' : string,
  'views' : bigint,
  'videoAssetId' : ExternalBlob,
  'description' : string,
  'likes' : bigint,
  'timestamp' : Time,
  'uploader' : Principal,
}
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[string, string], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createVideoPost' : ActorMethod<[string, string, ExternalBlob], string>,
  'deleteComment' : ActorMethod<[string, string], undefined>,
  'deleteVideoPost' : ActorMethod<[string], undefined>,
  'followUser' : ActorMethod<[Principal], undefined>,
  'getAllVideos' : ActorMethod<[], Array<PersistentVideoPost>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [PersistentUserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getComments' : ActorMethod<[string], Array<PersistentComment>>,
  'getFollowers' : ActorMethod<[Principal], Array<Principal>>,
  'getFollowing' : ActorMethod<[Principal], Array<Principal>>,
  'getTrendingVideos' : ActorMethod<[], Array<PersistentVideoPost>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [PersistentUserProfile]>,
  'getVideo' : ActorMethod<[string], [] | [PersistentVideoPost]>,
  'getVideosByUser' : ActorMethod<[Principal], Array<PersistentVideoPost>>,
  'hasUserLikedVideo' : ActorMethod<[string, Principal], boolean>,
  'incrementViewCount' : ActorMethod<[string], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'likeVideo' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[PersistentUserProfile], undefined>,
  'unfollowUser' : ActorMethod<[Principal], undefined>,
  'unlikeVideo' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];