/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const PersistentVideoPost = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'views' : IDL.Nat,
  'videoAssetId' : ExternalBlob,
  'description' : IDL.Text,
  'likes' : IDL.Nat,
  'timestamp' : Time,
  'uploader' : IDL.Principal,
});
export const PersistentUserProfile = IDL.Record({
  'bio' : IDL.Text,
  'displayName' : IDL.Text,
  'followerCount' : IDL.Nat,
  'followingCount' : IDL.Nat,
});
export const PersistentComment = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Time,
  'videoId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createVideoPost' : IDL.Func(
      [IDL.Text, IDL.Text, ExternalBlob],
      [IDL.Text],
      [],
    ),
  'deleteComment' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteVideoPost' : IDL.Func([IDL.Text], [], []),
  'followUser' : IDL.Func([IDL.Principal], [], []),
  'getAllVideos' : IDL.Func([], [IDL.Vec(PersistentVideoPost)], ['query']),
  'getCallerUserProfile' : IDL.Func(
      [],
      [IDL.Opt(PersistentUserProfile)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getComments' : IDL.Func([IDL.Text], [IDL.Vec(PersistentComment)], ['query']),
  'getFollowers' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getFollowing' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getTrendingVideos' : IDL.Func([], [IDL.Vec(PersistentVideoPost)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(PersistentUserProfile)],
      ['query'],
    ),
  'getVideo' : IDL.Func([IDL.Text], [IDL.Opt(PersistentVideoPost)], ['query']),
  'getVideosByUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(PersistentVideoPost)],
      ['query'],
    ),
  'hasUserLikedVideo' : IDL.Func(
      [IDL.Text, IDL.Principal],
      [IDL.Bool],
      ['query'],
    ),
  'incrementViewCount' : IDL.Func([IDL.Text], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likeVideo' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([PersistentUserProfile], [], []),
  'unfollowUser' : IDL.Func([IDL.Principal], [], []),
  'unlikeVideo' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const PersistentVideoPost = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'views' : IDL.Nat,
    'videoAssetId' : ExternalBlob,
    'description' : IDL.Text,
    'likes' : IDL.Nat,
    'timestamp' : Time,
    'uploader' : IDL.Principal,
  });
  const PersistentUserProfile = IDL.Record({
    'bio' : IDL.Text,
    'displayName' : IDL.Text,
    'followerCount' : IDL.Nat,
    'followingCount' : IDL.Nat,
  });
  const PersistentComment = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Time,
    'videoId' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createVideoPost' : IDL.Func(
        [IDL.Text, IDL.Text, ExternalBlob],
        [IDL.Text],
        [],
      ),
    'deleteComment' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteVideoPost' : IDL.Func([IDL.Text], [], []),
    'followUser' : IDL.Func([IDL.Principal], [], []),
    'getAllVideos' : IDL.Func([], [IDL.Vec(PersistentVideoPost)], ['query']),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(PersistentUserProfile)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getComments' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PersistentComment)],
        ['query'],
      ),
    'getFollowers' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getFollowing' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getTrendingVideos' : IDL.Func(
        [],
        [IDL.Vec(PersistentVideoPost)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(PersistentUserProfile)],
        ['query'],
      ),
    'getVideo' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PersistentVideoPost)],
        ['query'],
      ),
    'getVideosByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(PersistentVideoPost)],
        ['query'],
      ),
    'hasUserLikedVideo' : IDL.Func(
        [IDL.Text, IDL.Principal],
        [IDL.Bool],
        ['query'],
      ),
    'incrementViewCount' : IDL.Func([IDL.Text], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likeVideo' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([PersistentUserProfile], [], []),
    'unfollowUser' : IDL.Func([IDL.Principal], [], []),
    'unlikeVideo' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };